---
name: validate

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cfn-lint:
    name: cfn-lint
    runs-on: ubuntu-latest
    container:
      image: hansohn/cloudformation:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint templates
        run: cfn-lint templates/*.yaml
